apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-updater
spec:
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
    spec:
      containers:
      - name: cloudflare-updater
        image: ghcr.io/nyu058/cloudflare-dynamic-ip
        args:
        - -i
        - 300
        - example.com
        - www.example.com
        env:
          - name: CF_API_TOKEN 
            valueFrom:
              secretKeyRef: 
                name: cf-api-token 
                key: token
          - name: ZONE_ID 
            valueFrom:
              configMapKeyRef:
                name: cf-zone-id
                key: zone-id
---
apiVersion: v1
kind: Secret
metadata:
  name: cf-api-token
data:
  token: <your-token>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-zone-id
data:
  zone-id: <your-zone-id>